### ISSUE TITLE
Longhand PRE markup not honoured in Fandoc popups / hovers

### ISSUE THREAD

**Issue by SlimerDude** [xored/f4#40]
When previewing Fandoc comments, `pre>...<pre` notation is not honoured:
````
class Broken {
	**   This PRE markup works.
	** 
	** pre>
	** This PRE markup does not 
	** <pre
	Void main() {}
}
````
When you hover over the `main()` method, this is rendered:
![premarkup](https://cloud.githubusercontent.com/assets/3326741/5627435/c35456fe-958f-11e4-8e94-54ed60935e84.png)

**Comment by komaz** [comment]
Here's the relevant part of fandoc parsing in F4 IDE (in `f4uiText.FandocProvider#compile`):
```fantom
  protected Str compile(Str fandoc)
  {
    doc := FandocParser().parseStr(fandoc)
    buf := StrBuf()
    doc.write(HtmlDocWriter(buf.out))
    return buf.toStr
  }
```

Looks like we don't trim an extra space after two stars (`**`):
```fantom
class Broken {
    **   This PRE markup works.
    ** 
    ** pre>
    ** This PRE markup does not 
    ** <pre
    **
    **pre>
    **  But this PRE works!
    ** ahaha!
    **<pre
    Void main() {}
}
```

I wonder whether we should just always trim `**<space>` instead of `**`, or should we perform extra trimming at the beginnig when line starts with either `pre>` or `<pre`. I guess we need to check Fantom sources for the best practice.

F4 uses 1.0.63 version of `fandoc`, so maybe this behavior has been already fixed in `fandoc` itself

**Comment by komaz** [comment]
Here's how Fantom parser handles it (from `compiler#Tokenizer`):
```fantom
  private TokenVal? docComment()
  {
    // if doc is off, then just skip the line and be done
    if (!isDoc) { skipCommentSL; return null }

    while (cur == '*') consume
    if (cur == ' ') consume
    ...
```

i.e. a single optional space immediately after stars is consumed, same should be done in F4
