### ISSUE TITLE
Problems with 	external interpreter (F4 1.0.3, embedded Fantom 1.0.68)

### ISSUE THREAD

**Issue by martianov** [xored/f4#96]
Disclaimer: I have limited experience with Fantom so it may be 'not a bug but feature'

Steps to reproduce:
1. Add in F4 (v1.0.3 with embedded Fantom 1.0.68) external interpreter Fantom 1.0.59 through Preferences/Fantom/Interpreters.
2. Create new Fantom project using project specific interpreter 1.0.59

First strange thing - this project doesn't contain 'Fantom Native Libraries (Java)':
![f4_1_0_3-external-interpreter-no-java-libs](https://cloud.githubusercontent.com/assets/9569740/16839592/b6ab21fe-49f1-11e6-88ba-70511ead77bd.png)
but our rcptt tests expect it to be.

Second, when I tried run simple 'hello-world' using 1.0.59 application I got exception:
`Error: Could not find or load main class fanx.tools.Fan`

so I suspect that something wrong with it..

**Comment by SlimerDude** [comment]
I couldn't find an installation for Fantom 1.0.59 from the [downloads page](https://bitbucket.org/fantom/fan-1.0/downloads/) so I used Fantom 1.0.60 (which is still 5 years old!) and it all works okay. I get the `Fantom Native Libraries (Java)` and can run a `Hello World` program.

![f4-external-interpreter](https://cloud.githubusercontent.com/assets/3326741/16854152/988eebea-4a07-11e6-96c7-7018fb6f383b.png)

I did need to slightly patch the `F4LauchEnv`, which runs in the background of launched Fantom apps, to be compatible with older versions of Fantom. See pull request #97 

I use an external interpreter all the time and have never seen the above issue - maybe the problem is with the Fantom 1.0.59 installation. Try downloading a different Fantom version and see if the problem still exists for you.

**Comment by martianov** [comment]
Problem with "Fantom Native Libraries (Java)" was caused by bug in rcptt tests. And I don't understand how I could reproduced it.. Shortly, it was caused by incorrect adding of interpreter.

So I closed this issue. Sorry for the false alarm
